//! VBA's and Excel's named constants.

use super::value::V;

/// A constant by lower-case name.
pub fn get(name: &str) -> Option<V> {
    let s = |t: &str| Some(V::Str(t.to_owned()));
    let i = |n: i64| Some(V::Int(n));
    match name {
        "vbcrlf" | "vbnewline" => s("\r\n"),
        "vbcr" => s("\r"),
        "vblf" => s("\n"),
        "vbtab" => s("\t"),
        "vbnullstring" => s(""),
        "vbnullchar" => s("\0"),
        "vbback" => s("\u{8}"),
        "vbformfeed" => s("\u{c}"),
        "vbverticaltab" => s("\u{b}"),
        // MsgBox buttons and icons.
        "vbokonly" => i(0),
        "vbokcancel" => i(1),
        "vbabortretryignore" => i(2),
        "vbyesnocancel" => i(3),
        "vbyesno" => i(4),
        "vbretrycancel" => i(5),
        "vbcritical" => i(16),
        "vbquestion" => i(32),
        "vbexclamation" => i(48),
        "vbinformation" => i(64),
        "vbdefaultbutton1" => i(0),
        "vbdefaultbutton2" => i(256),
        "vbdefaultbutton3" => i(512),
        "vbapplicationmodal" => i(0),
        "vbsystemmodal" => i(4096),
        // MsgBox results.
        "vbok" => i(1),
        "vbcancel" => i(2),
        "vbabort" => i(3),
        "vbretry" => i(4),
        "vbignore" => i(5),
        "vbyes" => i(6),
        "vbno" => i(7),
        // Comparison, types, days.
        "vbbinarycompare" => i(0),
        "vbtextcompare" => i(1),
        "vbempty" => i(0),
        "vbnull" => i(1),
        "vbinteger" => i(2),
        "vblong" => i(3),
        "vbsingle" => i(4),
        "vbdouble" => i(5),
        "vbcurrency" => i(6),
        "vbdate" => i(7),
        "vbstring" => i(8),
        "vbobject" => i(9),
        "vberror" => i(10),
        "vbboolean" => i(11),
        "vbvariant" => i(12),
        "vbarray" => i(8192),
        "vbsunday" => i(1),
        "vbmonday" => i(2),
        "vbtuesday" => i(3),
        "vbwednesday" => i(4),
        "vbthursday" => i(5),
        "vbfriday" => i(6),
        "vbsaturday" => i(7),
        "vbusesystemdayofweek" => i(0),
        "vbobjecterror" => i(-2_147_221_504),
        "vbtrue" => i(-1),
        "vbfalse" => i(0),
        "vbblack" => i(0),
        "vbwhite" => i(0xFF_FFFF),
        "vbred" => i(0xFF),
        "vbgreen" => i(0xFF00),
        "vbblue" => i(0xFF_0000),
        "vbyellow" => i(0xFFFF),
        // Excel.
        "xlup" => i(-4162),
        "xldown" => i(-4121),
        "xltoleft" => i(-4159),
        "xltoright" => i(-4161),
        "xlshiftup" => i(-4162),
        "xlshifttoleft" => i(-4159),
        "xlshiftdown" => i(-4121),
        "xlshifttoright" => i(-4161),
        "xlwhole" => i(1),
        "xlpart" => i(2),
        "xlvalues" => i(-4163),
        "xlformulas" => i(-4123),
        "xlbyrows" => i(1),
        "xlbycolumns" => i(2),
        "xlnext" => i(1),
        "xlprevious" => i(2),
        "xlcalculationmanual" => i(-4135),
        "xlcalculationautomatic" => i(-4105),
        "xlcalculationsemiautomatic" => i(2),
        "xlerrdiv0" => i(2007),
        "xlerrna" => i(2042),
        "xlerrname" => i(2029),
        "xlerrnull" => i(2000),
        "xlerrnum" => i(2036),
        "xlerrref" => i(2023),
        "xlerrvalue" => i(2015),
        "xlsheetvisible" => i(-1),
        "xlsheethidden" => i(0),
        "xlsheetveryhidden" => i(2),
        "xlascending" => i(1),
        "xldescending" => i(2),
        "xlyes" => i(1),
        "xlno" => i(2),
        "xlguess" => i(0),
        "xlnone" => i(-4142),
        "xlautomatic" => i(-4105),
        "xlcenter" => i(-4108),
        "xlleft" => i(-4131),
        "xlright" => i(-4152),
        "xlpastevalues" => i(-4163),
        "xlpasteall" => i(-4104),
        "xlpasteformats" => i(-4122),
        "xlcelltypelastcell" => i(11),
        "xlcelltypeblanks" => i(4),
        "xlcelltypeconstants" => i(2),
        "xlcelltypeformulas" => i(-4123),
        "xla1" => i(1),
        "xlr1c1" => i(-4150),
        _ => None,
    }
}

/// Excel's error number of an error value's text (`CVErr(xlErrNA)`).
pub fn error_number(text: &str) -> i64 {
    match text {
        "#NULL!" => 2000,
        "#DIV/0!" => 2007,
        "#VALUE!" => 2015,
        "#REF!" => 2023,
        "#NAME?" => 2029,
        "#NUM!" => 2036,
        "#N/A" => 2042,
        _ => 2043,
    }
}

/// The text of an Excel error number.
pub fn error_text(n: i64) -> &'static str {
    match n {
        2000 => "#NULL!",
        2007 => "#DIV/0!",
        2015 => "#VALUE!",
        2023 => "#REF!",
        2029 => "#NAME?",
        2036 => "#NUM!",
        2042 => "#N/A",
        _ => "#GETTING_DATA",
    }
}
