//! The functions the formula engine knows, by the names Excel writes, with
//! the arguments of the common ones as Excel's Insert Function shows them.

/// Every function the engine computes: its name, and its arguments when
/// they are written down here (else empty). The names are the engine's own
/// English ones (one for each field of its function names).
pub fn list() -> Vec<(String, String)> {
    let Ok(language) = ironcalc_base::language::get_language("en") else {
        return Vec::new();
    };
    let f = &language.functions;
    let names: [&String; NAMES] = [
        &f.and,
        &f.r#false,
        &f.r#if,
        &f.iferror,
        &f.ifna,
        &f.ifs,
        &f.not,
        &f.or,
        &f.switch,
        &f.r#true,
        &f.xor,
        &f.r#let,
        &f.lambda,
        &f.log,
        &f.log10,
        &f.ln,
        &f.sin,
        &f.cos,
        &f.tan,
        &f.asin,
        &f.acos,
        &f.atan,
        &f.sinh,
        &f.cosh,
        &f.tanh,
        &f.asinh,
        &f.acosh,
        &f.atanh,
        &f.acot,
        &f.acoth,
        &f.cot,
        &f.coth,
        &f.csc,
        &f.csch,
        &f.sec,
        &f.sech,
        &f.abs,
        &f.pi,
        &f.sqrt,
        &f.sqrtpi,
        &f.atan2,
        &f.power,
        &f.max,
        &f.min,
        &f.product,
        &f.rand,
        &f.randbetween,
        &f.round,
        &f.rounddown,
        &f.roundup,
        &f.sum,
        &f.sumif,
        &f.sumifs,
        &f.choose,
        &f.column,
        &f.columns,
        &f.index,
        &f.indirect,
        &f.hlookup,
        &f.lookup,
        &f.r#match,
        &f.offset,
        &f.row,
        &f.rows,
        &f.vlookup,
        &f.xlookup,
        &f.sort,
        &f.sortby,
        &f.unique,
        &f.filter,
        &f.sequence,
        &f.randarray,
        &f.textsplit,
        &f.concatenate,
        &f.exact,
        &f.value,
        &f.t,
        &f.valuetotext,
        &f.concat,
        &f.find,
        &f.left,
        &f.len,
        &f.lower,
        &f.mid,
        &f.right,
        &f.search,
        &f.text,
        &f.trim,
        &f.unicode,
        &f.unichar,
        &f.r#char,
        &f.clean,
        &f.code,
        &f.asc,
        &f.arraytotext,
        &f.dollar,
        &f.findb,
        &f.fixed,
        &f.leftb,
        &f.lenb,
        &f.midb,
        &f.numbervalue,
        &f.proper,
        &f.replace,
        &f.replaceb,
        &f.rightb,
        &f.searchb,
        &f.upper,
        &f.isnumber,
        &f.isnontext,
        &f.istext,
        &f.islogical,
        &f.isblank,
        &f.iserr,
        &f.iserror,
        &f.isna,
        &f.na,
        &f.isref,
        &f.isodd,
        &f.iseven,
        &f.errortype,
        &f.formulatext,
        &f.isformula,
        &f.isomitted,
        &f.r#type,
        &f.sheet,
        &f.average,
        &f.averagea,
        &f.avedev,
        &f.averageif,
        &f.averageifs,
        &f.count,
        &f.counta,
        &f.countblank,
        &f.countif,
        &f.countifs,
        &f.maxifs,
        &f.minifs,
        &f.geomean,
        &f.year,
        &f.day,
        &f.month,
        &f.eomonth,
        &f.date,
        &f.datedif,
        &f.datevalue,
        &f.edate,
        &f.networkdays,
        &f.networkdaysintl,
        &f.time,
        &f.timevalue,
        &f.hour,
        &f.minute,
        &f.second,
        &f.today,
        &f.now,
        &f.days,
        &f.days360,
        &f.weekday,
        &f.weeknum,
        &f.workday,
        &f.workdayintl,
        &f.yearfrac,
        &f.isoweeknum,
        &f.pmt,
        &f.pv,
        &f.rate,
        &f.nper,
        &f.fv,
        &f.ppmt,
        &f.ipmt,
        &f.npv,
        &f.mirr,
        &f.irr,
        &f.xirr,
        &f.xnpv,
        &f.rept,
        &f.textafter,
        &f.textbefore,
        &f.textjoin,
        &f.substitute,
        &f.regexextract,
        &f.regexreplace,
        &f.regextest,
        &f.ispmt,
        &f.rri,
        &f.sln,
        &f.syd,
        &f.nominal,
        &f.effect,
        &f.pduration,
        &f.tbillyield,
        &f.tbillprice,
        &f.tbilleq,
        &f.dollarde,
        &f.dollarfr,
        &f.ddb,
        &f.db,
        &f.cumprinc,
        &f.cumipmt,
        &f.accrint,
        &f.accrintm,
        &f.besseli,
        &f.besselj,
        &f.besselk,
        &f.bessely,
        &f.erf,
        &f.erfprecise,
        &f.erfc,
        &f.erfcprecise,
        &f.bin2dec,
        &f.bin2hex,
        &f.bin2oct,
        &f.dec2bin,
        &f.dec2hex,
        &f.dec2oct,
        &f.hex2bin,
        &f.hex2dec,
        &f.hex2oct,
        &f.oct2bin,
        &f.oct2dec,
        &f.oct2hex,
        &f.bitand,
        &f.bitlshift,
        &f.bitor,
        &f.bitrshift,
        &f.bitxor,
        &f.complex,
        &f.imabs,
        &f.imaginary,
        &f.imargument,
        &f.imconjugate,
        &f.imcos,
        &f.imcosh,
        &f.imcot,
        &f.imcsc,
        &f.imcsch,
        &f.imdiv,
        &f.imexp,
        &f.imln,
        &f.imlog10,
        &f.imlog2,
        &f.impower,
        &f.improduct,
        &f.imreal,
        &f.imsec,
        &f.imsech,
        &f.imsin,
        &f.imsinh,
        &f.imsqrt,
        &f.imsub,
        &f.imsum,
        &f.imtan,
        &f.convert,
        &f.delta,
        &f.gestep,
        &f.subtotal,
        &f.exp,
        &f.fact,
        &f.factdouble,
        &f.sign,
        &f.radians,
        &f.degrees,
        &f.int,
        &f.even,
        &f.odd,
        &f.ceiling,
        &f.ceilingmath,
        &f.ceilingprecise,
        &f.floor,
        &f.floormath,
        &f.floorprecise,
        &f.isoceiling,
        &f.r#mod,
        &f.quotient,
        &f.mround,
        &f.trunc,
        &f.gcd,
        &f.lcm,
        &f.base,
        &f.decimal,
        &f.roman,
        &f.arabic,
        &f.combin,
        &f.combina,
        &f.sumsq,
        &f.n,
        &f.cell,
        &f.info,
        &f.sheets,
        &f.daverage,
        &f.dcount,
        &f.dget,
        &f.dmax,
        &f.dmin,
        &f.dsum,
        &f.dcounta,
        &f.dproduct,
        &f.dstdev,
        &f.dvar,
        &f.dvarp,
        &f.dstdevp,
        &f.betadist,
        &f.betainv,
        &f.binomdist,
        &f.binomdistrange,
        &f.binominv,
        &f.chisqdist,
        &f.chisqdistrt,
        &f.chisqinv,
        &f.chisqinvrt,
        &f.chisqtest,
        &f.confidencenorm,
        &f.confidencet,
        &f.covariancep,
        &f.covariances,
        &f.devsq,
        &f.expondist,
        &f.fdist,
        &f.fdistrt,
        &f.finv,
        &f.finvrt,
        &f.fisher,
        &f.fisherinv,
        &f.ftest,
        &f.gamma,
        &f.gammadist,
        &f.gammainv,
        &f.gammaln,
        &f.gammalnprecise,
        &f.hypgeomdist,
        &f.lognormdist,
        &f.lognorminv,
        &f.negbinomdist,
        &f.normdist,
        &f.norminv,
        &f.normsdist,
        &f.normsinv,
        &f.pearson,
        &f.phi,
        &f.poissondist,
        &f.standardize,
        &f.stdev,
        &f.disc,
        &f.fvschedule,
        &f.intrate,
        &f.pricedisc,
        &f.pricemat,
        &f.received,
        &f.yielddisc,
        &f.yieldmat,
        &f.duration,
        &f.mduration,
        &f.price,
        &f.r#yield,
        &f.oddfprice,
        &f.oddfyield,
        &f.oddlprice,
        &f.oddlyield,
        &f.coupdaybs,
        &f.coupdays,
        &f.coupdaysnc,
        &f.coupncd,
        &f.coupnum,
        &f.couppcd,
        &f.amordegrc,
        &f.amorlinc,
        &f.vdb,
        &f.stdevp,
        &f.stdevs,
        &f.stdeva,
        &f.stdevpa,
        &f.tdist,
        &f.tdist2t,
        &f.tdistrt,
        &f.tinv,
        &f.tinv2t,
        &f.ttest,
        &f.varp,
        &f.vars,
        &f.varpa,
        &f.vara,
        &f.weibulldist,
        &f.ztest,
        &f.chidist,
        &f.chiinv,
        &f.chitest,
        &f.confidence,
        &f.covar,
        &f.critbinom,
        &f.loginv,
        &f.betainvcompat,
        &f.binomdistcompat,
        &f.expondistcompat,
        &f.fdistcompat,
        &f.finvcompat,
        &f.ftestcompat,
        &f.gammadistcompat,
        &f.gammainvcompat,
        &f.modecompat,
        &f.normdistcompat,
        &f.norminvcompat,
        &f.normsinvcompat,
        &f.percentilecompat,
        &f.percentrankcompat,
        &f.poissoncompat,
        &f.quartilecompat,
        &f.rankcompat,
        &f.stdevpcompat,
        &f.tinvcompat,
        &f.ttestcompat,
        &f.varcompat,
        &f.varpcompat,
        &f.weibullcompat,
        &f.ztestcompat,
        &f.betadistcompat,
        &f.hypgeomdistcompat,
        &f.lognormdistcompat,
        &f.negbinomdistcompat,
        &f.normsdistcompat,
        &f.tdistcompat,
        &f.sumx2my2,
        &f.sumx2py2,
        &f.sumxmy2,
        &f.correl,
        &f.rsq,
        &f.intercept,
        &f.slope,
        &f.steyx,
        &f.forecast,
        &f.forecastlinear,
        &f.forecastets,
        &f.forecastetsconfint,
        &f.forecastetsseasonality,
        &f.forecastetsstat,
        &f.frequency,
        &f.growth,
        &f.linest,
        &f.logest,
        &f.modemult,
        &f.modesngl,
        &f.percentileexc,
        &f.percentileinc,
        &f.percentrankexc,
        &f.percentrankinc,
        &f.permut,
        &f.permutationa,
        &f.prob,
        &f.quartileexc,
        &f.quartileinc,
        &f.trend,
        &f.trimmean,
        &f.gauss,
        &f.harmean,
        &f.kurt,
        &f.large,
        &f.maxa,
        &f.median,
        &f.mina,
        &f.rankavg,
        &f.rankeq,
        &f.skew,
        &f.skewp,
        &f.small,
        &f.take,
        &f.drop,
        &f.tocol,
        &f.torow,
        &f.transpose,
        &f.mmult,
        &f.bycol,
        &f.byrow,
        &f.map,
        &f.reduce,
        &f.scan,
        &f.makearray,
        &f.address,
        &f.areas,
        &f.choosecols,
        &f.chooserows,
        &f.expand,
        &f.hstack,
        &f.vstack,
        &f.wrapcols,
        &f.wraprows,
        &f.xmatch,
        &f.trimrange,
        &f.mdeterm,
        &f.minverse,
        &f.munit,
        &f.multinomial,
        &f.seriessum,
        &f.sumproduct,
        &f.percentof,
    ];
    let mut out: Vec<(String, String)> = names
        .iter()
        .map(|n| {
            let args = arguments(n).unwrap_or_default().to_owned();
            ((*n).clone(), args)
        })
        .collect();
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out.dedup_by(|a, b| a.0 == b.0);
    out
}

/// How many names the engine has.
const NAMES: usize = 494;

/// The arguments of a common function, as Excel writes them.
fn arguments(name: &str) -> Option<&'static str> {
    Some(match name {
        "ABS" => "number",
        "AND" | "OR" | "XOR" => "logical1, [logical2], ...",
        "AVERAGE" | "AVERAGEA" | "MEDIAN" | "MODE" | "STDEV" | "STDEV.S" | "STDEV.P" | "VAR"
        | "VAR.S" | "VAR.P" | "MAX" | "MIN" | "MAXA" | "MINA" | "PRODUCT" | "SUM" | "SUMSQ"
        | "GEOMEAN" | "HARMEAN" => "number1, [number2], ...",
        "AVERAGEIF" | "SUMIF" => "range, criteria, [sum_range]",
        "AVERAGEIFS" => "average_range, criteria_range1, criteria1, ...",
        "SUMIFS" => "sum_range, criteria_range1, criteria1, ...",
        "COUNTIF" => "range, criteria",
        "COUNTIFS" => "criteria_range1, criteria1, ...",
        "MAXIFS" | "MINIFS" => "max_range, criteria_range1, criteria1, ...",
        "COUNT" | "COUNTA" => "value1, [value2], ...",
        "COUNTBLANK" => "range",
        "CHOOSE" => "index_num, value1, [value2], ...",
        "CONCAT" | "CONCATENATE" => "text1, [text2], ...",
        "TEXTJOIN" => "delimiter, ignore_empty, text1, ...",
        "DATE" => "year, month, day",
        "DATEDIF" => "start_date, end_date, unit",
        "DAY" | "MONTH" | "YEAR" => "serial_number",
        "WEEKDAY" => "serial_number, [return_type]",
        "WEEKNUM" => "serial_number, [return_type]",
        "EDATE" | "EOMONTH" => "start_date, months",
        "NETWORKDAYS" => "start_date, end_date, [holidays]",
        "WORKDAY" => "start_date, days, [holidays]",
        "TIME" => "hour, minute, second",
        "HOUR" | "MINUTE" | "SECOND" => "serial_number",
        "NOW" | "TODAY" | "PI" | "RAND" | "TRUE" | "FALSE" | "NA" => "",
        "RANDBETWEEN" => "bottom, top",
        "DAYS" => "end_date, start_date",
        "EXACT" => "text1, text2",
        "FIND" | "SEARCH" => "find_text, within_text, [start_num]",
        "IF" => "logical_test, value_if_true, [value_if_false]",
        "IFS" => "logical_test1, value_if_true1, ...",
        "IFERROR" => "value, value_if_error",
        "IFNA" => "value, value_if_na",
        "NOT" => "logical",
        "SWITCH" => "expression, value1, result1, [default_or_value2], ...",
        "INDEX" => "array, row_num, [column_num]",
        "MATCH" => "lookup_value, lookup_array, [match_type]",
        "XMATCH" => "lookup_value, lookup_array, [match_mode], [search_mode]",
        "VLOOKUP" => "lookup_value, table_array, col_index_num, [range_lookup]",
        "HLOOKUP" => "lookup_value, table_array, row_index_num, [range_lookup]",
        "XLOOKUP" => {
            "lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode]"
        }
        "LOOKUP" => "lookup_value, lookup_vector, [result_vector]",
        "OFFSET" => "reference, rows, cols, [height], [width]",
        "INDIRECT" => "ref_text, [a1]",
        "ROW" | "COLUMN" => "[reference]",
        "ROWS" | "COLUMNS" => "array",
        "TRANSPOSE" => "array",
        "UNIQUE" => "array, [by_col], [exactly_once]",
        "SORT" => "array, [sort_index], [sort_order], [by_col]",
        "FILTER" => "array, include, [if_empty]",
        "SEQUENCE" => "rows, [columns], [start], [step]",
        "LEFT" | "RIGHT" => "text, [num_chars]",
        "MID" => "text, start_num, num_chars",
        "LEN" | "LOWER" | "UPPER" | "PROPER" | "TRIM" | "CLEAN" | "VALUE" => "text",
        "REPLACE" => "old_text, start_num, num_chars, new_text",
        "SUBSTITUTE" => "text, old_text, new_text, [instance_num]",
        "REPT" => "text, number_times",
        "TEXT" => "value, format_text",
        "TEXTBEFORE" | "TEXTAFTER" => "text, delimiter, [instance_num], ...",
        "ISBLANK" | "ISERROR" | "ISNA" | "ISNUMBER" | "ISTEXT" | "ISLOGICAL" | "ISERR" => "value",
        "INT" | "EVEN" | "ODD" | "SIGN" | "SQRT" | "EXP" | "LN" | "LOG10" | "FACT" => "number",
        "LOG" => "number, [base]",
        "MOD" => "number, divisor",
        "POWER" => "number, power",
        "QUOTIENT" => "numerator, denominator",
        "ROUND" | "ROUNDUP" | "ROUNDDOWN" => "number, num_digits",
        "TRUNC" => "number, [num_digits]",
        "CEILING" | "FLOOR" | "MROUND" => "number, significance",
        "SUMPRODUCT" => "array1, [array2], ...",
        "SUBTOTAL" => "function_num, ref1, ...",
        "AGGREGATE" => "function_num, options, ref1, ...",
        "LARGE" | "SMALL" => "array, k",
        "RANK" | "RANK.EQ" | "RANK.AVG" => "number, ref, [order]",
        "PERCENTILE" | "PERCENTILE.INC" | "PERCENTILE.EXC" => "array, k",
        "QUARTILE" | "QUARTILE.INC" | "QUARTILE.EXC" => "array, quart",
        "CORREL" => "array1, array2",
        "FORECAST" | "FORECAST.LINEAR" => "x, known_ys, known_xs",
        "TREND" => "known_ys, [known_xs], [new_xs], [const]",
        "PMT" => "rate, nper, pv, [fv], [type]",
        "FV" => "rate, nper, pmt, [pv], [type]",
        "PV" => "rate, nper, pmt, [fv], [type]",
        "NPER" => "rate, pmt, pv, [fv], [type]",
        "RATE" => "nper, pmt, pv, [fv], [type], [guess]",
        "NPV" => "rate, value1, [value2], ...",
        "IRR" => "values, [guess]",
        "HYPERLINK" => "link_location, [friendly_name]",
        "LET" => "name1, name_value1, calculation_or_name2, ...",
        "LAMBDA" => "[parameter1, ...], calculation",
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn functions_listed() {
        let l = list();
        assert!(l.len() > 300, "{}", l.len());
        let get = |n: &str| l.iter().find(|f| f.0 == n).map(|f| f.1.as_str());
        assert_eq!(get("SUM"), Some("number1, [number2], ..."));
        assert_eq!(
            get("VLOOKUP"),
            Some("lookup_value, table_array, col_index_num, [range_lookup]")
        );
        // Newer functions without their file prefix.
        assert!(get("XLOOKUP").is_some());
        assert!(l.iter().all(|f| !f.0.starts_with("_xl")));
    }
}
